name: go_green_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# consider running `flutter pub upgrade --major-versions` for auto upgrade. 
dependencies:
  flutter:
    sdk: flutter

  # Stacked
  stacked: ^3.0.1
  stacked_services: ^0.9.8

  # Data Model
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  line_icons: ^2.0.1
  logger: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # see `analysis_options.yaml` file located at the root of app
  flutter_lints: ^2.0.0
  mockito: ^5.3.1
  build_runner:
  freezed:
  json_serializable:
  test_cov: ^1.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash:
  stacked_generator: ^0.8.1



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Bold.ttf
          weight: 700
        - asset: fonts/Oswald-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
